### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by NithinSethumadhavan** [fresearchgroup/performance-improvement-of-openedx#2]
Keep the documentation updated.  Mention the issues you faced and the steps you took to resolve them.

**Comment by abcabhishek** [comment]
In progress. Initial draft will be done in 1 day's time.

**Comment by abcabhishek** [comment]
https://docs.google.com/document/d/1ClTPfu3ZL9PyWc1ixN7hQEaDJaZ6AKJKHcnSjVdJPk8/edit?usp=sharing 

This link may be used to view the rough draft.
Regards,
Abhishek Chattopadhyay
